export const ICONS = {
  TRASH: "fa fa-trash",
  ARROW_RIGHT: "fa fa-arrow-right",
  ARROW_LEFT: "fa fa-arrow-left",
  LOADING: "fa fa-spinner fa-spin",
  MENU: "fa fa-bars",
  CLOSE: "fa fa-xmark",
  CARET_DOWN: "fa fa-caret-down",
  CARET_UP: "fa fa-caret-up",
  CHEVRON_LEFT: "fa fa-chevron-left",
  CHEVRON_RIGHT: "fa fa-chevron-right",
  CIRCLE: "fa fa-circle",
  PLAY: "fa fa-play",
  PLAY_PAUSE: "fa fa-play-pause",
  PAUSE: "fa fa-pause",
};
